// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfzdGXsVMjj9Zb9S6B5AEC-BjnRDqTYjk',
    appId: '1:959111052840:web:bb71b22cd6b3bb6058ff1d',
    messagingSenderId: '959111052840',
    projectId: 'dr-seta-efcc5',
    authDomain: 'dr-seta-efcc5.firebaseapp.com',
    storageBucket: 'dr-seta-efcc5.appspot.com',
    measurementId: 'G-K0H89DV7F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNX9j8agho5Skkf4vdRGRp-1vF99y4Ebs',
    appId: '1:959111052840:android:ff2f30b86c4c84e058ff1d',
    messagingSenderId: '959111052840',
    projectId: 'dr-seta-efcc5',
    storageBucket: 'dr-seta-efcc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi9twr2F1hT5eyj6zaHFznM36NOX2SvEY',
    appId: '1:959111052840:ios:9068a13e54e10bb058ff1d',
    messagingSenderId: '959111052840',
    projectId: 'dr-seta-efcc5',
    storageBucket: 'dr-seta-efcc5.appspot.com',
    iosClientId: '959111052840-siblc3ko33jufa9gnj8q9auvbdr6ir46.apps.googleusercontent.com',
    iosBundleId: 'appinventor.aimosaabhmat.drseta.drSeta',
  );
}
